spring.application.name=retailiq-backend

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:retailiq}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
logging.level.org.springframework.security=INFO