services:

  mysql:
    image: mysql:8.4
    container_name: retailiq-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: always

  backend:
    build:
      context: ./backend/retailiq-backend

    container_name: retailiq-backend

    depends_on:
      - mysql

    environment:
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GROQ_API_KEY: ${GROQ_API_KEY}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8081:8080"

    restart: always

  frontend:
    build:
      context: ./retailiq-frontend

    container_name: retailiq-frontend

    depends_on:
      - backend

    ports:
      - "5173:80"

    restart: always

volumes:
  mysql_data: